version: '3.8'

services:
  database:
    image: postgres:latest
    ports:
      - 5432:5432
    restart: always
    environment:
      - POSTGRES_DB=dev_sorteio
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data 
  server:
    image: node:lts-alpine
    ports:
      - ${PORT}:${PORT}
    restart: unless-stopped
    working_dir: /app
    env_file:
      - ./server/.env
    environment:
      - POSTGRES_HOST=database
      - POSTGRES_DB=dev_sorteio
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./server:/app
    command: 'npm run dev'
    depends_on:
      - database
  client:
    image: node:lts-alpine
    ports:
      - 3000:3000
    restart: unless-stopped
    working_dir: /app
    env_file:
      - ./client/.env
    volumes:
      - ./client:/app
    command: 'npm run dev'
    depends_on:
      - server                                                                       

volumes:
  postgres_data:
  server:
  client: