version: "3.8"

services:
  postgres:
    image: "postgres:latest"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    env_file:
      - /home/ubuntu/.env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
  server:
    build: ./server
    restart: always
    env_file:
      - /home/ubuntu/.env
    ports:
      - 3000:3000
    depends_on:
      - postgres
  nginx:
    build: ./client
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./certbot/conf:/etc/nginx/ssl
      - ./certbot/data:/usr/share/nginx/html/letsencrypt
    depends_on:
      - server
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/conf:/etc/nginx/ssl
      - ./certbot/data:/usr/share/nginx/html/letsencrypt
    command: certonly --webroot --webroot-path=/var/www/certbot --email mlucas4330@gmail.com --agree-tos --no-eff-email --force-renewal -d ninjasena.online -d www.ninjasena.online
volumes:
  postgres_data:
