version: '3.8'

services:
  database:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: development_sorteio
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASS}
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data 
  api:
    build: ./server
    environment:
      POSTGRES_HOST: database
      POSTGRES_DB: development_sorteio
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASS: ${POSTGRES_PASS}
    depends_on:
      - database
  client:
    build: ./client
    depends_on:
      - api                                                                       

volumes:
  postgres_data: