version: "3.8"

services:
  postgres:
    image: "postgres:latest"
    restart: always
    env_file:
      - /home/ubuntu/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
  server:
    build: ./server
    restart: always
    env_file:
      - /home/ubuntu/.env
    ports:
      - 3000:3000
    depends_on:
      - postgres
  client-nginx:
    build: ./client
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/www/:/var/www/certbot
    ports:
      - 80:80
      - 443:443
    depends_on:
      - server
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
volumes:
  postgres_data:
