version: "3.8"

services:
  postgres:
    image: "postgres:latest"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    env_file:
      - /home/ubuntu/.env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
  server:
    build: ./server
    restart: always
    env_file:
      - /home/ubuntu/.env
    ports:
      - 3000:3000
    depends_on:
      - postgres
  client:
    build: ./client
    depends_on:
      - server
  nginx:
    image: nginx:latest
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./app/dist:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - client
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot --webroot-path /var/www/certbot --force-renewal --email mlucas4330@gmail.com -d ninjasena.online -d www.ninjasena.online --agree-tos
volumes:
  postgres_data:
