version: '3.8'

services:
  database:
    image: postgres:latest
    ports:
      - 5432:5432
    restart: always
    environment:
      - POSTGRES_DB=dev_sorteio
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data 
  api:
    build: ./server
    ports:
      - 3000:3000
    restart: always
    environment:
      - POSTGRES_HOST=database
      - POSTGRES_DB=dev_sorteio
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    depends_on:
      - database
  client:
    build: ./client
    ports:
      - 5173:5173
    restart: always
    environment:
      - VITE_URL=${VITE_URL}
    depends_on:
      - api                                                                       

volumes:
  postgres_data: