name: CICD
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Git Pull and Restart Containers
        run: |
          ssh -i ${{ secrets.SSH_PRIVATE_KEY_PATH }} ubuntu@ec2-18-228-48-227.sa-east-1.compute.amazonaws.com "cd /home/ubuntu/apps/sorteio && git pull origin main && docker-compose down && docker-compose up"
